#!/bin/bash

export TWITTER_CONSUMER_KEY=""
export TWITTER_CONSUMER_SECRET=""
export TWITTER_ACCESS_TOKEN=""
export TWITTER_ACCESS_TOKEN_SECRET=""

export TWITTER_ID_TO_INSULTIFY=""
export TWITTER_USERNAME_TO_INSULTIFY=""

export CURSING_SERVER=""
export CURSING_PORT=""